# Set prefix to Ctrl+a
# unbind C-b
# set -g prefix C-a
# bind C-a send-prefix

# Enable 256-color and true-color (24-bit) support in tmux
set -g default-terminal "screen-256color" # Set terminal type for 256-color support
set -ga terminal-overrides ",*256col*:Tc" # Override to enable true-color for compatible terminals

# General
set -g set-clipboard on         # Use system clipboard
set -g detach-on-destroy off    # Don't exit from tmux when closing a session
set -g escape-time 0            # Remove delay for exiting insert mode with ESC in Neovim
set -g history-limit 1000000    # Increase history size (from 2,000)
set -g mouse on                 # Enable mouse support
set -g status-interval 3        # Update the status bar every 3 seconds (default: 15 seconds)
set -g allow-passthrough on     # Allow programs in the pane to bypass tmux (e.g. for image preview)
set -g status-position bottom

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Split panes using | and -
bind c new-window -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

set-window-option -g mode-keys vi

# Switch panes using Alt-arrow without prefix
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Use vim arrow keys to resize
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

# Start selecting text with "v"
bind-key -T copy-mode-vi 'v' send -X begin-selection 

# Copy text with "y"
bind -T copy-mode-vi 'y' send-keys -X copy-pipe-and-cancel "pbcopy"

# Paste yanked text with "Prefix + P" ("Prefix + p" goes to previous window)
bind P paste-buffer

# Don't exit copy mode when dragging with mouse
unbind -T copy-mode-vi MouseDragEnd1Pane


# tpm plugin manager
set -g @plugin 'tmux-plugins/tpm'

# List of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator' # Enable navigating between nvim and tmux
set -g @plugin 'tmux-plugins/tmux-resurrect'    # Persist tmux sessions after computer restart
set -g @plugin 'tmux-plugins/tmux-continuum'    # Automatically saves sessions every 15 minutes
set -g @plugin 'hendrikmi/tmux-cpu-mem-monitor' # CPU and memory info

# Style
gray_light="#D8DEE9"
gray_medium="#ABB2BF"
gray_dark="#3B4252"
green_soft="#A3BE8C"
blue_muted="#81A1C1"
cyan_soft="#88C0D0"

set -g @vim_navigator_mapping_left "C-Left C-h"  # use C-h and C-Left
set -g @vim_navigator_mapping_right "C-Right C-l"
set -g @vim_navigator_mapping_up "C-k"
set -g @vim_navigator_mapping_down "C-j"
set -g @vim_navigator_mapping_prev ""  # removes the C-\ binding

set -g status-position top
set -g status-left-length 100
set -g status-style "fg=${gray_light},bg=default"
set -g status-left "#[fg=${green_soft},bold] #S #[fg=${gray_light},nobold] | "
set -g status-right " #{cpu}   #{mem} "
set -g window-status-current-format "#[fg=${cyan_soft},bold]  #[underscore]#I:#W"
set -g window-status-format " #I:#W"
set -g message-style "fg=${gray_light},bg=default"
set -g mode-style "fg=${gray_dark},bg=${blue_muted}"
set -g pane-border-style "fg=${gray_dark}"
set -g pane-active-border-style "fg=${green_soft}"

# Resurrect
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

bind r source-file ~/.config/tmux/tmux.conf \; display "Config Reloaded!"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
