general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 150
    on-timeout = bash -c '[[ "$(cat /tmp/hypridle_mode_status 2>/dev/null)" != "afk" ]] && brightnessctl -s set 10'
    on-resume = bash -c '[[ "$(cat /tmp/hypridle_mode_status 2>/dev/null)" != "afk" ]] && brightnessctl -r'
}

listener {
    timeout = 150
    on-timeout = bash -c '[[ "$(cat /tmp/hypridle_mode_status 2>/dev/null)" != "afk" ]] && brightnessctl -sd rgb:kbd_backlight set 0'
    on-resume = bash -c '[[ "$(cat /tmp/hypridle_mode_status 2>/dev/null)" != "afk" ]] && brightnessctl -rd rgb:kbd_backlight'
}

listener {
    timeout = 300
    on-timeout = bash -c '[[ "$(cat /tmp/hypridle_mode_status 2>/dev/null)" != "afk" ]] && loginctl lock-session'
}

listener {
    timeout = 330
    on-timeout = bash -c '[[ "$(cat /tmp/hypridle_mode_status 2>/dev/null)" != "afk" ]] && hyprctl dispatch dpms off'
    on-resume = bash -c '[[ "$(cat /tmp/hypridle_mode_status 2>/dev/null)" != "afk" ]] && hyprctl dispatch dpms on && brightnessctl -r'
}

listener {
    timeout = 1800
    on-timeout = bash -c '[[ "$(cat /tmp/hypridle_mode_status 2>/dev/null)" != "afk" ]] && systemctl suspend'
}

